### ISSUE TITLE
Consider a more flexible chunking model for distributing spark arrays

### ISSUE THREAD

**Issue by shoyer** [bolt-project/bolt#56]
Looking through the source code, it appears that the internal design of `BoltArraySpark` distributes arrays by splitting them along axes.

This is a similar but less flexible than the distributed data model of [dask.array](http://dask.pydata.org/en/latest/array.html), which allows for partial chunking along axes. The `BoltArraySpark` model is equivalent to the dask.array chunking model if chunk sizes are restricted to size 1 or the full length of an array dimension.
 
In some cases, more flexible chunking (e.g., as implemented with the HDF5 file format) can be very convenient. For example, it allows for reasonable worst case performance with both space and time queries on 3D arrays with dimensions `(x, y, t)`. Or with large 2D images (e.g., mosaics of satellite imagery), there really isn't any alternative to chunking along multiple dimensions at once.

Have you thought about this approach for your distributed spark arrays? Is this more flexible model more complex than you want to deal with? Or maybe you think it's unnecessary because of the high performance of Spark for reshuffling data?

**Comment by freeman-lab** [comment]
@shoyer thanks for the great thoughts. I'll share some replies here, and some of this will be available in the full doc site (which will go up in the next couple days!).

Top-level, we do support the kind of chunking you're describing, but it's not part of the core object definition.

The core definition of the Spark bolt array uses keys to represent one subset of dimensions, and values to represent the others. The keys are the "distributed" dimension, and the values are local arrays. So, as you say, it's not breaking things into chunks in the dask sense. 

*However*, we do exactly the dask-style chunking during transposes, which helps make that distributed operation much more performant (by shuffling fewer large chunks). This was a trick we learned in Thunder for doing images -> time series conversions. It's quite flexible, and allows chunking by any amount along any axis. But we don't (yet) expose it as part of the top-level API, partly because resulting object is more complex to work with in terms of indexing.

We could definitely explore opening up this "chunked" intermediate object and making it easier for users to create and work with them. Any further details on the use case, and what functionality would be useful/necessary, would be much appreciated!

**Comment by jwittenbach** [comment]
Implemented in #67.
